/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.ObjWeka;
import negocio.TreeJ482;
import weka.classifiers.trees.J48;
import weka.core.Instances;
import weka.gui.treevisualizer.PlaceNode2;
import weka.gui.treevisualizer.TreeVisualizer;

/**
 *
 * @author David Torrez
 */
public class ventana extends javax.swing.JFrame {
    
    HashMap<String, String> arrayNewInstacia;
    TreeJ482<ObjWeka> tree;
    J48 j48;
    Instances data;
    static final String RUTA="src/datos/test.arff";
    
    

    /**
     * Creates new form ventana
     */
    public ventana() {
        tree = new TreeJ482<>();
        arrayNewInstacia = new HashMap<>();
        j48 = new J48();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jcbox1 = new javax.swing.JComboBox<>();
        jcbox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbox3 = new javax.swing.JComboBox<>();
        jcbox5 = new javax.swing.JComboBox<>();
        jcbox6 = new javax.swing.JComboBox<>();
        jcbox8 = new javax.swing.JComboBox<>();
        jcbox7 = new javax.swing.JComboBox<>();
        jcbox10 = new javax.swing.JComboBox<>();
        jcbox9 = new javax.swing.JComboBox<>();
        jcbox12 = new javax.swing.JComboBox<>();
        jcbox11 = new javax.swing.JComboBox<>();
        jcbox14 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jcbox13 = new javax.swing.JComboBox<>();
        jcbox20 = new javax.swing.JComboBox<>();
        jcbox16 = new javax.swing.JComboBox<>();
        jcbox15 = new javax.swing.JComboBox<>();
        jcbox17 = new javax.swing.JComboBox<>();
        jcbox18 = new javax.swing.JComboBox<>();
        jcbox19 = new javax.swing.JComboBox<>();
        jbtnEjecutar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Consultas de Creditos");

        jcbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<0", "0<=X<200", ">=200", "no checking" }));
        jcbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox1ActionPerformed(evt);
            }
        });

        jcbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=10", ">10", "<=36", ">36" }));

        jLabel5.setText("Duracion");

        jLabel6.setText("Proposito del Credito");

        jcbox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "new car", "used car", "furniture/equipment", "radio/tv", "domestic appliance", "repairs", "education", "vacation", "retraining", "business", "other" }));

        jLabel7.setText("Monto de crédito");

        jLabel8.setText("Estado de ahorro");

        jLabel9.setText("Empleo");

        jLabel10.setText("Compromiso a plazos");

        jLabel11.setText("Estado personal");

        jLabel12.setText("Otros partidos");

        jLabel13.setText("Residencia desde");

        jLabel14.setText("Magnitud de la propiedad");

        jLabel15.setText("Años");

        jLabel4.setText("Historial de Credito");

        jcbox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no credits/all paid", "all paid", "existing paid", "delayed previously", "critical/other existing credit" }));

        jcbox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=4151", ">4151", "<=6761", ">6761", "<=9572", ">9572" }));
        jcbox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox5ActionPerformed(evt);
            }
        });

        jcbox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<100", "100<=X<500", "500<=X<1000", ">=1000", "no known savings" }));

        jcbox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=2", ">2" }));

        jcbox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "unemployed", "<1", "1<=X<4", "4<=X<7", ">=7" }));

        jcbox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "co applicant", "guarantor" }));

        jcbox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male div/sep", "female div/dep/mar", "male single", "male mar/wid", "female single" }));

        jcbox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "real estate", "life insurance", "car", "no known property" }));

        jcbox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=1", ">1" }));

        jcbox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bank", "stores", "none" }));

        jLabel16.setText("Otros planes de pago");

        jLabel17.setText("Alojamiento");

        jLabel18.setText("Créditos existentes");

        jLabel19.setText("Trabajo");

        jLabel3.setText("Estado de Comprovacion");

        jLabel20.setText("Dependientes num");

        jLabel21.setText("Teléfono propio");

        jLabel22.setText("Trabajador extranjero");

        jcbox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=10", ">10" }));

        jcbox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));

        jcbox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=2", ">2" }));

        jcbox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rent", "own", "for free" }));

        jcbox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "unemp/unskilled non res", "unskilled resident", "skilled", "high qualif/self emp/mgmt" }));

        jcbox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=1", ">1" }));

        jcbox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "yes" }));

        jbtnEjecutar.setText("Consultar");
        jbtnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEjecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jcbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jcbox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel19)
                                    .addComponent(jcbox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17)
                                    .addComponent(jcbox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jcbox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jcbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jcbox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addComponent(jcbox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jcbox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jcbox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel22)
                                    .addComponent(jcbox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jcbox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jbtnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel14)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jbtnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Ver Arbol");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbox1ActionPerformed

    private void jcbox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbox5ActionPerformed

    private void jbtnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEjecutarActionPerformed
        // TODO add your handling code here:
        List<String> Insta = new ArrayList<>();
        if(estanLlenosLosCampos(Insta)){
            //pasamos la ruta para ejecutar el codigo
//            arrayNewInstacia = tree.cargarDatos(data, Insta);
//            for (String string : Insta) {
//                System.out.println(string);
//            }
            
            try {
                data = new Instances(new BufferedReader(new FileReader(RUTA)));
                tree.algoritmoJ48(j48,data);


                arrayNewInstacia = tree.cargarDatos(data, Insta);
                boolean validarCredito = tree.validarCredito(arrayNewInstacia);
//
                if(validarCredito){
                    Insta.add("good");
                    JOptionPane.showMessageDialog(rootPane, "Su credito ha sido aceptado", "AGENTE DE CREDITOS", HEIGHT);
//
                }else{
                    Insta.add("bad");
                    JOptionPane.showMessageDialog(rootPane, "Su credito no ha sido aceptado", "AGENTE DE CREDITOS", HEIGHT);
//
                }
//
                insertarNewInstanciaDeCredito(Insta);
//                limpiarCampos();
            } catch (IOException e) {
//                
                System.out.println("Error al realizar el algoritmo");
                System.out.println(e.toString());
//                
            }
            
            
        }else{
            JOptionPane.showConfirmDialog(rootPane, "Llene todo los campos", "Mensaje", WIDTH);
        }
    }//GEN-LAST:event_jbtnEjecutarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    try {
        // train classifier
         data = new Instances(new BufferedReader(new FileReader(RUTA)));
        data.setClassIndex(data.numAttributes() - 1);
        j48.buildClassifier(data);
//        System.out.println(cls.graph());
//        System.out.println(cls.globalInfo());

        // display classifier
        final javax.swing.JFrame jf = 
          new javax.swing.JFrame("Visualizador de Arbol J48 : Weka");
        jf.setSize(500,400);
        jf.getContentPane().setLayout(new BorderLayout());
        TreeVisualizer tv;

        tv = new TreeVisualizer(null,j48.graph(),new PlaceNode2());
        
        jf.getContentPane().add(tv, BorderLayout.CENTER);
        jf.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            jf.dispose();
          }
        });

        jf.setVisible(true);
        tv.fitToScreen();
    } catch (Exception ex) {
            Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnEjecutar;
    private javax.swing.JComboBox<String> jcbox1;
    private javax.swing.JComboBox<String> jcbox10;
    private javax.swing.JComboBox<String> jcbox11;
    private javax.swing.JComboBox<String> jcbox12;
    private javax.swing.JComboBox<String> jcbox13;
    private javax.swing.JComboBox<String> jcbox14;
    private javax.swing.JComboBox<String> jcbox15;
    private javax.swing.JComboBox<String> jcbox16;
    private javax.swing.JComboBox<String> jcbox17;
    private javax.swing.JComboBox<String> jcbox18;
    private javax.swing.JComboBox<String> jcbox19;
    private javax.swing.JComboBox<String> jcbox2;
    private javax.swing.JComboBox<String> jcbox20;
    private javax.swing.JComboBox<String> jcbox3;
    private javax.swing.JComboBox<String> jcbox4;
    private javax.swing.JComboBox<String> jcbox5;
    private javax.swing.JComboBox<String> jcbox6;
    private javax.swing.JComboBox<String> jcbox7;
    private javax.swing.JComboBox<String> jcbox8;
    private javax.swing.JComboBox<String> jcbox9;
    // End of variables declaration//GEN-END:variables

    private boolean estanLlenosLosCampos(List<String> l) {
        boolean salida=true;
        l.add((String) jcbox1.getSelectedItem());
        String duracion="";
        switch((String) jcbox2.getSelectedItem()){
            case "<=10" : duracion = "10";  break;
            case ">10" : duracion = "11";  break;
            case "<=36" : duracion = "36";  break;
            case ">36" : duracion = "37";  break;
        }
        l.add(duracion);
        l.add((String) jcbox3.getSelectedItem());
        l.add((String) jcbox4.getSelectedItem());
        String creadit_amount="";
        switch((String) jcbox5.getSelectedItem()){
            case "<=4151" : creadit_amount = "4151";  break;
            case ">4151" : creadit_amount = "4152";  break;
            case "<=6761" : creadit_amount = "6761";  break;
            case ">6761" : creadit_amount = "6762";  break;
            case "<=9572" : creadit_amount = "9572";  break;
            case ">9572" : creadit_amount = "9573";  break;
        }
        l.add(creadit_amount);
        l.add((String) jcbox6.getSelectedItem());
        l.add((String) jcbox7.getSelectedItem());
        String compromiso_a_plazo="";
        switch((String) jcbox8.getSelectedItem()){
            case "<=2" : compromiso_a_plazo = "2";  break;
            case ">2" : compromiso_a_plazo = "3";  break;
        }
        l.add(compromiso_a_plazo);
        l.add((String) jcbox9.getSelectedItem());
        l.add((String) jcbox10.getSelectedItem());
        String residencia_desde="";
        switch((String) jcbox11.getSelectedItem()){
            case "<=1" : residencia_desde = "1";  break;
            case ">1" : residencia_desde = "2";  break;
        }
        l.add(residencia_desde);
        l.add((String) jcbox12.getSelectedItem());
        String año="age";
        switch((String) jcbox13.getSelectedItem()){
            case "<=10" : año = "10";  break;
            case ">10" : año = "11";  break;
        }
        l.add(año);
        l.add((String) jcbox14.getSelectedItem());
        l.add((String) jcbox15.getSelectedItem());
        String credito_existente="";
        switch((String) jcbox16.getSelectedItem()){
            case "<=2" : credito_existente = "2";  break;
            case ">2" : credito_existente = "3";  break;
        }
        l.add(credito_existente);
        l.add((String) jcbox17.getSelectedItem());
        String nroDependientes="";
        switch((String) jcbox18.getSelectedItem()){
            case "<=1" : nroDependientes = "1";  break;
            case ">1" : nroDependientes = "2";  break;
        }
        l.add(nroDependientes);
        l.add((String) jcbox19.getSelectedItem());
        l.add((String) jcbox20.getSelectedItem());
        
        for (String string : l) {
            if(string.equals("Seleccione")){
                salida=false; break;
            }
            
        }
        return salida;
    }
    
    public void limpiarCampos(){
        
        jcbox1.setSelectedIndex(0);
        jcbox2.setSelectedIndex(0);
        jcbox3.setSelectedIndex(0);
        jcbox4.setSelectedIndex(0);
        jcbox5.setSelectedIndex(0);
        jcbox6.setSelectedIndex(0);
        jcbox7.setSelectedIndex(0);
        jcbox8.setSelectedIndex(0);
        jcbox9.setSelectedIndex(0);
        jcbox10.setSelectedIndex(0);
        jcbox11.setSelectedIndex(0);
        jcbox12.setSelectedIndex(0);
        jcbox13.setSelectedIndex(0);
        jcbox14.setSelectedIndex(0);
        jcbox15.setSelectedIndex(0);
        jcbox16.setSelectedIndex(0);
        jcbox17.setSelectedIndex(0);
        jcbox18.setSelectedIndex(0);
        jcbox19.setSelectedIndex(0);
        jcbox20.setSelectedIndex(0);
        
    }

    private void insertarNewInstanciaDeCredito(List<String> arrayNewInstacia) {
        tree.addNewInstace(arrayNewInstacia);
    }
}
